[project]
name = "cosmo_data_tools"
version = "0.1.0"
description = "Convenience classes for plotting cosmological data"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
